#pragma once

#define TAPPING_TERM 180
#define COMBO_TERM 50

#define PERMISSIVE_HOLD
#define COMBO_ALLOW_ACTION_KEYS
#define CHORDAL_HOLD

#define MOUSE_TURBO_CLICK_PERIOD 50
#define MOUSE_TURBO_CLICK_KEY MS_BTN1
#define ENABLE_COMPILE_KEYCODE
